spring:
  application:
    name: "jdbc-spy"

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: "jdbc:log4jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
